trigger:
 branches:
   include:
     - main

pool:david-pool
stages:
  - stage: 
    displayName: createinfraRG
    jobs:
      - job: 
        displayName: terraform init plan apply
        steps:
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'david-SVC'
              backendAzureRmResourceGroupName: 'rg-david'
              backendAzureRmStorageAccountName: 'david12321'
              backendAzureRmContainerName: 'david-container'
              backendAzureRmKey: 'terraformnew.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'david-SVC'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'david-SVC'